#!/usr/bin/env bash
# ============================================================================
# Session Initialization — v{{VERSION}}
# Event: SessionStart (Claude Code v2 hook format)
# Generated by {{PROJECT_NAME}} harness-marketplace plugin
# Non-blocking; output is shown to the user at session start.
# Note: SessionStart hooks do not receive tool_input — _parse.sh is not sourced
# here to avoid blocking on stdin.
# ============================================================================
set -uo pipefail

# shellcheck disable=SC1091
source "$(dirname "$0")/_log.sh"

# ═══ GENERATED RULES (overwritten on upgrade) ═══

PROJECT_NAME="{{PROJECT_NAME}}"
PLUGIN_VERSION="{{VERSION}}"

echo "============================================"
echo "  ${PROJECT_NAME} — Session Init"
echo "  Harness Plugin v${PLUGIN_VERSION}"
echo "============================================"
echo ""

# --- Check required tools ---
MISSING_TOOLS=()

check_tool() {
  local tool_name="$1"
  local display_name="${2:-$1}"
  if command -v "$tool_name" >/dev/null 2>&1; then
    local version
    version=$("$tool_name" --version 2>/dev/null | head -n1 || echo "installed")
    echo "  [OK] ${display_name}: ${version}"
  else
    echo "  [MISSING] ${display_name}: not found"
    MISSING_TOOLS+=("$tool_name")
  fi
}

echo "Required tools:"
check_tool "node" "Node.js"
check_tool "git" "Git"

# Check for package manager (npm, pnpm, yarn, or bun)
echo ""
echo "Package manager:"
PM_FOUND=false
for pm in pnpm yarn bun npm; do
  if command -v "$pm" >/dev/null 2>&1; then
    pm_version=$("$pm" --version 2>/dev/null | head -n1 || echo "installed")
    echo "  [OK] ${pm}: ${pm_version}"
    PM_FOUND=true
    break
  fi
done

if [[ "$PM_FOUND" = false ]]; then
  echo "  [MISSING] No package manager found (npm, pnpm, yarn, or bun)"
  MISSING_TOOLS+=("package-manager")
fi

# --- Report missing tools ---
if [[ ${#MISSING_TOOLS[@]} -gt 0 ]]; then
  echo ""
  echo "[WARN] Missing tools: ${MISSING_TOOLS[*]}"
  echo "       Some operations may not work correctly."
fi

# --- Project info ---
echo ""
echo "Project info:"

# Git branch
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
  echo "  Branch: ${BRANCH}"

  # Check for uncommitted changes
  if git diff --quiet 2>/dev/null && git diff --staged --quiet 2>/dev/null; then
    echo "  Working tree: clean"
  else
    CHANGED=$(git diff --name-only 2>/dev/null | wc -l | tr -d ' ')
    STAGED=$(git diff --staged --name-only 2>/dev/null | wc -l | tr -d ' ')
    echo "  Working tree: ${CHANGED} modified, ${STAGED} staged"
  fi
fi

# Node dependencies check
if [[ -f "package.json" ]]; then
  if [[ -d "node_modules" ]]; then
    echo "  Dependencies: installed"
  else
    echo "  Dependencies: NOT installed (run your package manager install)"
  fi
fi

# --- Dev server check (optional, non-blocking) ---
echo ""
echo "Dev server:"
DEV_SERVER_RUNNING=false

# Check common dev server ports
for port in 3000 3001 5173 5174 4200 8080 8000; do
  # Use /dev/tcp for portability across bash environments
  if (echo >/dev/tcp/127.0.0.1/"$port") 2>/dev/null; then
    echo "  [RUNNING] Dev server detected on port ${port}"
    DEV_SERVER_RUNNING=true
    break
  fi
done

if [[ "$DEV_SERVER_RUNNING" = false ]]; then
  echo "  [NOT RUNNING] No dev server detected on common ports"
  echo "  (This is informational only — start manually if needed)"
fi

# --- Orchestration entrypoint tip ---
echo ""
echo "Tip: 새 작업은 '/project-harness \"설명\"' 으로 시작하세요."
echo "     (plan → implement → verify 파이프라인 자동 실행. 자세한 안내는 ./CLAUDE.md 참고)"

echo ""
echo "============================================"
echo "  Session ready."
echo "============================================"

# ═══ CUSTOM RULES BELOW (preserved on upgrade) ═══

# Add your own session initialization steps here.
# They will be preserved when the plugin is upgraded.
#
# Example: Load environment-specific config
#   if [[ -f ".env.local" ]]; then
#     echo "  [INFO] Local environment config detected"
#   fi
#
# Example: Check for required services
#   if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
#     echo "  [OK] Docker is running"
#   fi

exit 0
